import type Song from '@/types/Song'

export const AnimationProject: Song[] = [
  {
    title: 'Reason!!',
    idols: ['315 STARS'],
    JOY: '424125',
    DAM: '4059-67',
    tags: ['ANIMATION PROJECT'],
  },
  {
    title: '流星PARADE',
    idols: ['Jupiter', 'DRAMATIC STARS', 'S.E.M'],
    JOY: '424858',
    DAM: '4060-82',
    tags: ['ANIMATION PROJECT'],
  },
  {
    title: '夏時間グラフィティ',
    idols: ['Beit', 'High×Joker', 'W'],
    JOY: '426012',
    DAM: '4400-80',
    tags: ['ANIMATION PROJECT'],
  },
  {
    title: 'TOMORROW DIAMOND',
    idols: ['Beit'],
    JOY: '424869',
    DAM: '4060-83',
    tags: ['ANIMATION PROJECT'],
  },
  {
    title: 'From Teacher To Future!',
    idols: ['S.E.M'],
    JOY: '424870',
    DAM: '4060-80',
    tags: ['ANIMATION PROJECT'],
  },
  {
    title: 'AFTER THE RAIN',
    idols: ['W'],
    JOY: '424871',
    DAM: '4060-81',
    tags: ['ANIMATION PROJECT'],
  },
  {
    title: 'Over AGAIN',
    idols: ['Jupiter'],
    JOY: '425657',
    DAM: '4400-68',
    tags: ['ANIMATION PROJECT'],
  },
  {
    title: 'Sunset★Colors',
    idols: ['High×Joker'],
    JOY: '425826',
    DAM: '4400-70',
    tags: ['ANIMATION PROJECT'],
  },
  {
    title: 'ARRIVE TO STAR',
    idols: ['DRAMATIC STARS'],
    JOY: '425825',
    DAM: '4400-75',
    tags: ['ANIMATION PROJECT'],
  },
  {
    title: 'GLORIOUS RO@D',
    idols: ['315 STARS'],
    JOY: '426742',
    DAM: '4476-44',
    tags: ['ANIMATION PROJECT'],
  },
  // アニメBD特典曲
  {
    title: 'DIVE to GRAVITATION',
    idols: ['Jupiter'],
    JOY: undefined,
    DAM: undefined,
    tags: ['アニメBD特典曲'],
  },
  {
    title: '冬の日のエトランゼ',
    idols: ['DRAMATIC STARS', 'Beit'],
    JOY: undefined,
    DAM: '4402-46',
    tags: ['315 St@rry Collaboration', 'アニメBD特典曲'],
  },
  {
    title: 'いつかこの瞬間に名前をつけるなら',
    idols: ['High×Joker', 'W'],
    JOY: undefined,
    DAM: '4403-06',
    tags: ['アニメBD特典曲', '315 St@rry Collaboration'],
  },
  {
    title: 'Secret! Playful! Drive!',
    idols: ['S.E.M', 'Jupiter'],
    JOY: undefined,
    DAM: '4403-13',
    tags: ['アニメBD特典曲', '315 St@rry Collaboration'],
  },
  {
    title: '嗚呼、情熱に星は輝く〜315プロダクション社歌〜',
    idols: ['プロデューサー＆山村賢 with 齋藤孝司'],
    JOY: undefined,
    DAM: '4424-52',
    tags: ['アニメBD特典曲'],
  },
  {
    title: '315 Steelo!',
    idols: [
      '天道輝',
      'ピエール',
      '渡辺みのり',
      '伊瀬谷四季',
      '蒼井享介',
      '硲道夫',
      '若里春名',
      '舞田類',
    ],
    JOY: undefined,
    DAM: undefined,
    tags: ['アニメBD特典曲'],
  },
]
