import type Song from '@/types/Song'

export const FifthAnniv: Song[] = [
  {
    title: 'PRIDE STAR',
    idols: ['315 ALLSTARS'],
    JOY: '445404',
    DAM: '4501-79',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'PRIDE STAR(G@ME VERSION)',
    idols: ['315 ALLSTARS'],
    JOY: undefined,
    DAM: '4478-79',
    tags: ['5th ANNIVERSARY DISC', 'G@ME VERSION'],
  },
  {
    title: 'ASTERISK',
    idols: ['DRAMATIC STARS'],
    JOY: '446345',
    DAM: '4507-28',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'オモイノウタ',
    idols: ['神速一魂'],
    JOY: '446344',
    DAM: '4507-23',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'Waving FLAGS',
    idols: ['F-LAGS'],
    JOY: '446343',
    DAM: '4507-32',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'Fine Day! Find Way!',
    idols: ['DRAMATIC STARS', '神速一魂', 'F-LAGS'],
    JOY: '446375',
    DAM: '4507-29',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'Great Sympathy',
    idols: ['W'],
    JOY: '447514',
    DAM: '4513-21',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'Present For You!!!!! ~A day in the café~',
    idols: ['Café Parade'],
    JOY: '447611',
    DAM: '4513-13',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'はんどめいど・きみはーと！',
    idols: ['もふもふえん'],
    JOY: '447610',
    DAM: '4513-32',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'ミュージアムジカ',
    idols: ['W', 'Café Parade', 'もふもふえん'],
    JOY: '447609',
    DAM: '4510-49',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'スリーブレス',
    idols: ['FRAME'],
    JOY: '447972',
    DAM: '4510-69',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: '√EVOLUTION',
    idols: ['S.E.M'],
    JOY: '448063',
    DAM: '4513-20',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'Make New Legend',
    idols: ['Legenders'],
    JOY: '448062',
    DAM: '4513-17',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'Bet your intuition!',
    idols: ['FRAME', 'S.E.M', 'Legenders'],
    JOY: '448061',
    DAM: '4513-14',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'mermaid fermata',
    idols: ['Altessimo'],
    JOY: '448981',
    DAM: '4520-05',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: '祝彩！',
    idols: ['彩'],
    JOY: '449050',
    DAM: '4520-32',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'SEASON IN THE FIVE',
    idols: ['High×Joker'],
    JOY: '448978',
    DAM: '4520-12',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'Singing Explorers',
    idols: ['Altessimo', '彩', 'High×Joker'],
    JOY: '448977',
    DAM: '4515-92',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: '運命光年',
    idols: ['Jupiter'],
    JOY: '485757',
    DAM: '4521-93',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'Avenue Illusion!',
    idols: ['Beit'],
    JOY: '485756',
    DAM: '4521-95',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'PROOF OF ONESELF',
    idols: ['THE 虎牙道'],
    JOY: '485755',
    DAM: '4521-92',
    tags: ['5th ANNIVERSARY DISC'],
  },
  {
    title: 'いつかのトライアングル',
    idols: ['Jupiter', 'Beit', 'THE 虎牙道'],
    JOY: '485754',
    DAM: '4521-94',
    tags: ['5th ANNIVERSARY DISC'],
  },
]
