import type Song from '@/types/Song'

export const GrowingSignal: Song[] = [
  {
    title: 'Growing Smiles!',
    idols: ['315 ALLSTARS'],
    JOY: undefined,
    DAM: '4558-31',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: "We're the one",
    idols: ['C.FIRST'],
    JOY: '495497',
    DAM: '4572-77',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Not Alone',
    idols: ['C.FIRST'],
    JOY: '614627',
    DAM: '4572-78',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Plus 1 Good Day!',
    idols: ['FRAME'],
    JOY: '610607',
    DAM: '4576-16',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'SOOTHING PLACE',
    idols: ['FRAME'],
    JOY: '611585',
    DAM: '4576-17',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Pavé Étoiles',
    idols: ['Café Parade'],
    JOY: '497866',
    DAM: '4581-65',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Teatime Cliché',
    idols: ['Café Parade'],
    JOY: '614214',
    DAM: '4581-64',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Time Before Time',
    idols: ['Legenders'],
    JOY: '496960',
    DAM: '4601-09',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'PERMAFROST',
    idols: ['Legenders'],
    JOY: '614671',
    DAM: '4601-10',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'いとをかし！～一彩×合彩～',
    idols: ['彩'],
    JOY: '497880',
    DAM: '4584-52',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: '彩リノ歌',
    idols: ['彩'],
    JOY: '615004',
    DAM: '4584-53',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'はるかぜバトン',
    idols: ['もふもふえん'],
    JOY: '498588',
    DAM: '3294-83',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'そだてっ！たいむかぷせる',
    idols: ['もふもふえん'],
    JOY: '613090',
    DAM: '3294-84',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Infinite Octave!',
    idols: ['Altessimo'],
    JOY: '610606',
    DAM: '3294-79',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Sign of Hope',
    idols: ['Altessimo'],
    JOY: '616039',
    DAM: '3294-80',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'K.now O.nly',
    idols: ['THE 虎牙道'],
    JOY: '499896',
    DAM: '3294-04',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'CATCH ME IF YOU CAN',
    idols: ['THE 虎牙道'],
    JOY: '613474',
    DAM: '3294-05',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Made in「 ♪ 」',
    idols: ['F-LAGS'],
    JOY: '610605',
    DAM: '3308-77',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Casually!',
    idols: ['F-LAGS'],
    JOY: '615534',
    DAM: '3308-78',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'ROUTE77',
    idols: ['神速一魂'],
    JOY: '611909',
    DAM: '3340-86',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'タソガレドキ、Bluesy',
    idols: ['神速一魂'],
    JOY: '615532',
    DAM: '3373-96',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Inner Dignity',
    idols: ['Jupiter'],
    JOY: '612081',
    DAM: '3337-48',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Before long, DELIGHT',
    idols: ['Jupiter'],
    JOY: '615725',
    DAM: '3337-49',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Multiple Entertainment Show!',
    idols: ['S.E.M'],
    JOY: '613024',
    DAM: '3337-56',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Dance in the school!',
    idols: ['S.E.M'],
    JOY: '615726',
    DAM: '3337-57',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Change to Chance',
    idols: ['DRAMATIC STARS'],
    JOY: '613432',
    DAM: '3340-84',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Rainy Memories',
    idols: ['DRAMATIC STARS'],
    JOY: '613946',
    DAM: '3345-10',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Take a StuMp!',
    idols: ['315 ALLSTARS'],
    JOY: '613802',
    DAM: '3330-76',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'True Horizon',
    idols: ['天ヶ瀬冬馬', '天道輝', '天峰秀'],
    JOY: '613877',
    DAM: '3342-48',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'VIVA!!ファミリーリズム',
    idols: ['W'],
    JOY: '614348',
    DAM: '3340-85',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Watchword',
    idols: ['W'],
    JOY: '614434',
    DAM: '3373-92',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Platinum MASK',
    idols: ['Beit'],
    JOY: '615038',
    DAM: '3345-36',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'MIRROR of TRUTH',
    idols: ['Beit'],
    JOY: '615425',
    DAM: '3345-37',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'JOYFUL HEART MAKER',
    idols: ['High×Joker'],
    JOY: '615856',
    DAM: '3350-72',
    tags: ['GROWING SIGN@L'],
  },
  {
    title: 'Toward Pole Star',
    idols: ['High×Joker'],
    JOY: '615827',
    DAM: '3350-73',
    tags: ['GROWING SIGN@L'],
  },
]
