import type Song from '@/types/Song'

export const NewStageEpisode: Song[] = [
  {
    title: 'NEXT STAGE!',
    idols: ['315 ALLSTARS'],
    JOY: '486841',
    DAM: '4532-58',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: 'わんだー×まーちんぐ！',
    idols: ['もふもふえん'],
    JOY: '486843',
    DAM: '4529-60',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: 'Hungry?',
    idols: ['THE 虎牙道'],
    JOY: '486842',
    DAM: '4529-58',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: 'Radiant Letter',
    idols: ['Jupiter'],
    JOY: '487312',
    DAM: '4532-59',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: 'Delicious Delivery',
    idols: ['Café Parade'],
    JOY: '487311',
    DAM: '4532-56',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: 'Secret Ornament',
    idols: ['Beit'],
    JOY: '493966',
    DAM: '4534-18',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: '喜怒哀楽万国共通 -Burn it up!-',
    idols: ['神速一魂'],
    JOY: '496473',
    DAM: '4534-17',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: 'Attacca Scenery',
    idols: ['Altessimo'],
    JOY: '498602',
    DAM: '4534-62',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: 'Smiles In Wonderland!',
    idols: ['High×Joker'],
    JOY: '498601',
    DAM: '4534-66',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: 'YELL OF DELIGHT',
    idols: ['W'],
    JOY: '493968',
    DAM: '4537-24',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: 'FOCUS ON YOUR LIFE',
    idols: ['Legenders'],
    JOY: '493967',
    DAM: '4537-29',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: 'リビングアイズヒーロー',
    idols: ['FRAME'],
    JOY: '498754',
    DAM: '4541-12',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: 'GOOD NEW MORNING',
    idols: ['DRAMATIC STARS'],
    JOY: '498660',
    DAM: '4541-11',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: "Happy's Birthday",
    idols: ['S.E.M'],
    JOY: '498755',
    DAM: '4544-13',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: '装 -So Beautiful-',
    idols: ['彩'],
    JOY: '498820',
    DAM: '4544-12',
    tags: ['NEW STAGE EPISODE'],
  },
  {
    title: "Hope's Journey",
    idols: ['F-LAGS'],
    JOY: '498819',
    DAM: '4544-14',
    tags: ['NEW STAGE EPISODE'],
  },
]
