import type Song from '@/types/Song'

export const OriginalPieces: Song[] = [
  {
    title: 'THE FIRST STAR',
    idols: ['天道輝'],
    JOY: '691133',
    DAM: '3771-78',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'GOLD ～No.79～',
    idols: ['山下次郎'],
    JOY: '691758',
    DAM: '3771-67',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'だいぶ・いんとぅ・にゅ～・わあるど！',
    idols: ['猫柳キリオ'],
    JOY: '691759',
    DAM: '3771-81',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: '我が混沌のサバト・マリアージュ',
    idols: ['アスラン＝ベルゼビュートⅡ世'],
    JOY: '691760',
    DAM: '3771-53',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: '新世代ワールド・ビッグスター！',
    idols: ['橘志狼'],
    JOY: '691761',
    DAM: '3771-62',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'Flying Hawk',
    idols: ['鷹城恭二'],
    JOY: '692296',
    DAM: '3772-61',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'ぴんとこな ～蝶よ華よ～',
    idols: ['華村翔真'],
    JOY: '692308',
    DAM: '3772-53',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'Happy-Go-Unlucky!',
    idols: ['木村龍'],
    JOY: '692309',
    DAM: '3772-62',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'Echoes My Note',
    idols: ['神楽麗'],
    JOY: '692311',
    DAM: '3772-59',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: '羽ばたきのMy Soul',
    idols: ['秋月涼'],
    JOY: '692312',
    DAM: '3772-56',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: '約束はドリーミングフライト',
    idols: ['柏木翼'],
    JOY: '692785',
    DAM: '3778-49',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'サイコーCOUNT UP!',
    idols: ['伊瀬谷四季'],
    JOY: '692784',
    DAM: '3778-39',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'Piece Montee',
    idols: ['東雲荘一郎'],
    JOY: '692783',
    DAM: '3778-48',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'ふわもこシフォンなゆめのなか♪',
    idols: ['姫野かのん'],
    JOY: '692782',
    DAM: '3778-50',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'Undiscovered WORLD',
    idols: ['古論クリス'],
    JOY: '692781',
    DAM: '3778-41',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'ROMANTIC SHAKER',
    idols: ['伊集院北斗'],
    JOY: '695513',
    DAM: '3780-58',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'Because',
    idols: ['桜庭薫'],
    JOY: '695514',
    DAM: '3780-61',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: '流るゝ風の如く ～和敬清寂～',
    idols: ['清澄九郎'],
    JOY: '695515',
    DAM: '3780-68',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'フェイバリットに踊らせて',
    idols: ['水嶋咲'],
    JOY: '695516',
    DAM: '3780-67',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'Sanctuary World',
    idols: ['都築圭'],
    JOY: '695517',
    DAM: '3780-70',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: '“W”onderful Tactics!',
    idols: ['蒼井享介'],
    JOY: '698074',
    DAM: '3789-73',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: '威風堂々と',
    idols: ['黒野玄武'],
    JOY: '697571',
    DAM: '3789-74',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'RULE～牙ヲ穿テヨ～',
    idols: ['牙崎漣'],
    JOY: '697572',
    DAM: '3789-75',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'ほっぷ・すてっぷ・ハイ、しーぷ！',
    idols: ['岡村直央'],
    JOY: '697573',
    DAM: '3789-76',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'Sweep Your Gloom',
    idols: ['葛之葉雨彦'],
    JOY: '698073',
    DAM: '3789-77',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'HAPPY×HAPPYミーティング',
    idols: ['天ヶ瀬冬馬'],
    JOY: '423992',
    DAM: '3791-27',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: '青春！サティスファクション',
    idols: ['若里春名'],
    JOY: '423991',
    DAM: '3791-24',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'GO AHEAD SMILE!',
    idols: ['信玄誠司'],
    JOY: '423990',
    DAM: '3791-25',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: '漢一貫ロックン・ロール',
    idols: ['紅井朱雀'],
    JOY: '423989',
    DAM: '3791-18',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'ROAD TO THE FUTURE',
    idols: ['円城寺道流'],
    JOY: '423988',
    DAM: '3791-12',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'Flowing Freedom',
    idols: ['北村想楽'],
    JOY: '423987',
    DAM: '3791-31',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'BACK FLIP☆EMOTION',
    idols: ['御手洗翔太'],
    JOY: '423677',
    DAM: '3792-30',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'ナツゾラRecords',
    idols: ['榊夏来'],
    JOY: '423676',
    DAM: '3792-31',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'A CUP OF HAPPINESS',
    idols: ['神谷幸広'],
    JOY: '423675',
    DAM: '3792-36',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'その場所へ行くために -KEEP ON FIGHTING-',
    idols: ['大河タケル'],
    JOY: '423674',
    DAM: '3792-38',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: '…掲げよう、偽りなき自分を。',
    idols: ['九十九一希'],
    JOY: '423673',
    DAM: '3792-28',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'Cherish BOUQUET',
    idols: ['渡辺みのり'],
    JOY: '425166',
    DAM: '4059-03',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'Genuine feelings',
    idols: ['冬美旬'],
    JOY: '423885',
    DAM: '4059-04',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'Learning Message',
    idols: ['硲道夫'],
    JOY: '423884',
    DAM: '4059-06',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'ハートフル・パトローラー',
    idols: ['握野英雄'],
    JOY: '423883',
    DAM: '4058-86',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'HANAMARU LIFE',
    idols: ['兜大吾'],
    JOY: '423882',
    DAM: '4058-93',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: '魔法のステアー',
    idols: ['ピエール'],
    JOY: '425363',
    DAM: '4062-18',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'PRECIOUS TONE',
    idols: ['秋山隼人'],
    JOY: '425359',
    DAM: '4062-32',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: '“W”orldwide Ambitions!',
    idols: ['蒼井悠介'],
    JOY: '425358',
    DAM: '4062-34',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'THIS IS IT!',
    idols: ['舞田類'],
    JOY: '425357',
    DAM: '4062-37',
    tags: ['ORIGIN@L PIECES'],
  },
  {
    title: 'ワンホール=ワンダーランド！',
    idols: ['卯月巻緒'],
    JOY: '425356',
    DAM: '4062-25',
    tags: ['ORIGIN@L PIECES'],
  },
]
