import type Song from '@/types/Song'

export const Others: Song[] = [
  {
    title: 'Beyond The Dream',
    idols: ['315 ALLSTARS'],
    JOY: '692693',
    DAM: '3777-87',
  },
  {
    title: 'Beyond The Dream(G@ME VERSION)',
    idols: ['315 ALLSTARS'],
    JOY: undefined,
    DAM: '4541-57',
    tags: ['G@ME VERSION'],
  },
  {
    title: 'なんどでも笑おう',
    idols: ['THE IDOLM@STER FIVE STARS!!!!!'],
    JOY: '486586',
    DAM: '4527-66',
  },
  {
    title: 'VOY@GER',
    idols: ['THE IDOLM@STER FIVE STARS!!!!!'],
    JOY: '492198',
    DAM: '4551-90',
  },
  {
    title: '幻想のUtopia',
    idols: [
      'ピエール',
      '蒼井悠介',
      '蒼井享介',
      '握野英雄',
      '木村龍',
      '秋山隼人',
      '冬美旬',
      '榊夏来',
      '若里春名',
      '紅井朱雀',
      '東雲荘一郎',
      'アスラン＝ベルゼビュートⅡ世',
      '岡村直央',
      '硲道夫',
      '大河タケル',
      '牙崎漣',
      '天峰秀',
      '花園百々人',
      '眉見鋭心',
    ],
    JOY: undefined,
    DAM: undefined,
  },
  {
    title: '安寧のDystopia',
    idols: [
      '天ヶ瀬冬馬',
      '伊集院北斗',
      '都築圭',
      '神楽麗',
      '渡辺みのり',
      '信玄誠司',
      '華村翔真',
      '清澄九郎',
      '伊瀬谷四季',
      '神谷幸広',
      '卯月巻緒',
      '水嶋咲',
      '橘志狼',
      '舞田類',
      '山下次郎',
      '円城寺道流',
      '兜大吾',
      '九十九一希',
      '葛之葉雨彦',
      '北村想楽',
    ],
    JOY: undefined,
    DAM: undefined,
  },
  {
    title: 'CRYST@LOUD',
    idols: ['THE IDOLM@STER FIVE STARS!!!!!'],
    JOY: '617215',
    DAM: '3350-30',
  },
]
