import type Song from '@/types/Song'

export const StartingLine: Song[] = [
  {
    title: 'BRAND NEW FIELD',
    idols: ['Jupiter'],
    JOY: '673880',
    DAM: '3730-64',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'BRAND NEW FIELD(G@ME VERSION)',
    idols: ['Jupiter'],
    JOY: undefined,
    DAM: '4475-15',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: 'Planet scape',
    idols: ['Jupiter'],
    JOY: '673787',
    DAM: '3732-62',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'STARLIGHT CELEBRATE!',
    idols: ['DRAMATIC STARS'],
    JOY: '673789',
    DAM: '3730-68',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'STARLIGHT CELEBRATE!(G@ME VERSION)',
    idols: ['DRAMATIC STARS'],
    JOY: undefined,
    DAM: '4475-17',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: 'DRAMATIC NONFICTION',
    idols: ['DRAMATIC STARS'],
    JOY: '673790',
    DAM: '3732-61',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'スマイル・エンゲージ',
    idols: ['Beit'],
    JOY: '676587',
    DAM: '3738-44',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'スマイル・エンゲージ(G@ME VERSION)',
    idols: ['Beit'],
    JOY: undefined,
    DAM: '4475-19',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: '想いはETERNITY',
    idols: ['Beit'],
    JOY: '676586',
    DAM: '3738-45',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'HIGH JUMP NO LIMIT',
    idols: ['High×Joker'],
    JOY: '676571',
    DAM: '3738-46',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'HIGH JUMP NO LIMIT(G@ME VERSION)',
    idols: ['High×Joker'],
    JOY: undefined,
    DAM: '4475-18',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: 'JOKER↗オールマイティ',
    idols: ['High×Joker'],
    JOY: '676570',
    DAM: '3738-47',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'VICTORY BELIEVER',
    idols: ['W'],
    JOY: '679628',
    DAM: '3747-36',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'VICTORY BELIEVER(G@ME VERSION)',
    idols: ['W'],
    JOY: undefined,
    DAM: '4475-16',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: 'Pleasure Forever...',
    idols: ['W'],
    JOY: '687405',
    DAM: '3747-35',
    tags: ['ST@RTING LINE'],
  },
  {
    title: '∞ Possibilities',
    idols: ['S.E.M'],
    JOY: '681297',
    DAM: '3747-31',
    tags: ['ST@RTING LINE'],
  },
  {
    title: '∞ Possibilities(G@ME VERSION)',
    idols: ['S.E.M'],
    JOY: undefined,
    DAM: '4475-65',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: 'Study Equal Magic!',
    idols: ['S.E.M'],
    JOY: '687404',
    DAM: '3747-32',
    tags: ['ST@RTING LINE'],
  },
  {
    title: '喝彩！ ～花鳥風月～',
    idols: ['彩'],
    JOY: '682271',
    DAM: '3756-41',
    tags: ['ST@RTING LINE'],
  },
  {
    title: '喝彩！ ～花鳥風月～(G@ME VERSION)',
    idols: ['彩'],
    JOY: undefined,
    DAM: '4475-62',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: '和風堂々！～WAnderful NIPPON!～',
    idols: ['彩'],
    JOY: '685183',
    DAM: '3756-42',
    tags: ['ST@RTING LINE'],
  },
  {
    title: '勇敢なるキミへ',
    idols: ['FRAME'],
    JOY: '682272',
    DAM: '3756-27',
    tags: ['ST@RTING LINE'],
  },
  {
    title: '勇敢なるキミへ(G@ME VERSION)',
    idols: ['FRAME'],
    JOY: undefined,
    DAM: '4475-67',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: 'MISSION is ピースフル！',
    idols: ['FRAME'],
    JOY: '685184',
    DAM: '3756-26',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'バーニン・クールで輝いて',
    idols: ['神速一魂'],
    JOY: '685486',
    DAM: '3762-69',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'バーニン・クールで輝いて(G@ME VERSION)',
    idols: ['神速一魂'],
    JOY: undefined,
    DAM: '4475-64',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: 'オレたちの最強伝説 ～一世一代、破羅駄威棲！～',
    idols: ['神速一魂'],
    JOY: '685487',
    DAM: '3762-68',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'Café Parade!',
    idols: ['Café Parade'],
    JOY: '686102',
    DAM: '3762-51',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'Café Parade!(G@ME VERSION)',
    idols: ['Café Parade'],
    JOY: undefined,
    DAM: '4475-14',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: 'A La Carte FREEDOM♪',
    idols: ['Café Parade'],
    JOY: '686101',
    DAM: '3762-50',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'The 1st Movement ～未来のための二重奏～',
    idols: ['Altessimo'],
    JOY: '687759',
    DAM: '3766-43',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'The 1st Movement ～未来のための二重奏～(G@ME VERSION)',
    idols: ['Altessimo'],
    JOY: undefined,
    DAM: '4475-61',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: 'Never end「Opus」',
    idols: ['Altessimo'],
    JOY: '687760',
    DAM: '3766-42',
    tags: ['ST@RTING LINE'],
  },
  {
    title: '強く尊き獣たち',
    idols: ['THE 虎牙道'],
    JOY: '687762',
    DAM: '3766-49',
    tags: ['ST@RTING LINE'],
  },
  {
    title: '強く尊き獣たち(G@ME VERSION)',
    idols: ['THE 虎牙道'],
    JOY: undefined,
    DAM: '4475-63',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: '情熱…FIGHTER',
    idols: ['THE 虎牙道'],
    JOY: '687763',
    DAM: '3766-50',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'うぇるかむ・はぴきらパーク！',
    idols: ['もふもふえん'],
    JOY: '691074',
    DAM: '3769-32',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'うぇるかむ・はぴきらパーク！(G@ME VERSION)',
    idols: ['もふもふえん'],
    JOY: undefined,
    DAM: '4475-68',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: 'もっふ・いんざぼっくす♪',
    idols: ['もふもふえん'],
    JOY: '691075',
    DAM: '3769-33',
    tags: ['ST@RTING LINE'],
  },
  {
    title: '夢色VOYAGER',
    idols: ['F-LAGS'],
    JOY: '691093',
    DAM: '3769-17',
    tags: ['ST@RTING LINE'],
  },
  {
    title: '夢色VOYAGER(G@ME VERSION)',
    idols: ['F-LAGS'],
    JOY: undefined,
    DAM: '4475-66',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: 'With…STORY',
    idols: ['F-LAGS'],
    JOY: '691092',
    DAM: '3769-16',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'Legacy of Spirit',
    idols: ['Legenders'],
    JOY: '691091',
    DAM: '3769-22',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'Legacy of Spirit(G@ME VERSION)',
    idols: ['Legenders'],
    JOY: undefined,
    DAM: '4475-20',
    tags: ['ST@RTING LINE', 'G@ME VERSION'],
  },
  {
    title: 'String of Fate',
    idols: ['Legenders'],
    JOY: '691090',
    DAM: '3769-23',
    tags: ['ST@RTING LINE'],
  },
  {
    title: 'DRIVE A LIVE',
    idols: ['315 STARS'],
    JOY: '673788',
    DAM: '3730-93',
    tags: ['ST@RTING LINE'],
  },
]
