import type Song from '@/types/Song'

export const WorldTreasure: Song[] = [
  {
    title: '永遠なる四銃士',
    idols: ['天道輝', '握野英雄', '紅井朱雀', '葛之葉雨彦'],
    JOY: '429194',
    DAM: '4424-18',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: 'トレジャー・パーティー！',
    idols: ['蒼井悠介', '木村龍', '若里春名'],
    JOY: '429942',
    DAM: '4427-49',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: 'Baile Apasionado',
    idols: ['橘志狼', '硲道夫', '牙崎漣'],
    JOY: '431621',
    DAM: '4437-88',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: '千客万来ニーハオサァカス！',
    idols: ['御手洗翔太', '渡辺みのり', '大河タケル', '兜大吾'],
    JOY: '433147',
    DAM: '4457-26',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: 'ALOHA! HAPPY CREATOR!',
    idols: ['水嶋咲', '姫野かのん', '舞田類'],
    JOY: '434873',
    DAM: '4457-33',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: 'Hallo, Freunde!',
    idols: ['伊集院北斗', '都築圭', '冬美旬', 'アスラン＝ベルゼビュートⅡ世'],
    JOY: '436511',
    DAM: '4464-38',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: 'Purely&Kindly',
    idols: ['ピエール', '蒼井享介', '清澄九郎', '榊夏来'],
    JOY: '438475',
    DAM: '4469-30',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: 'Sugaring Off Party!',
    idols: ['神楽麗', '秋山隼人', '卯月巻緒', '岡村直央'],
    JOY: '440558',
    DAM: '4476-70',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: '眠らぬ夜にスパシーバ！',
    idols: ['神谷幸広', '山下次郎', '古論クリス'],
    JOY: '441763',
    DAM: '4477-09',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: 'My pen light, SMILE',
    idols: ['柏木翼', '華村翔真', '東雲荘一郎', '円城寺道流'],
    JOY: '443914',
    DAM: '4483-40',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: 'もくろみインディアNight',
    idols: ['天ヶ瀬冬馬', '猫柳キリオ', '秋月涼'],
    JOY: '444979',
    DAM: '4501-78',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: 'Your Nobility',
    idols: ['桜庭薫', '黒野玄武', '九十九一希'],
    JOY: '447255',
    DAM: '4509-36',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: 'Welcome to Japan!',
    idols: ['鷹城恭二', '信玄誠司', '伊瀬谷四季', '北村想楽'],
    JOY: '448238',
    DAM: '4513-59',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: 'MEET THE WORLD',
    idols: ['315 STARS'],
    JOY: '429193',
    DAM: '4424-66',
    tags: ['WORLD TRE@SURE'],
  },
  {
    title: 'MEET THE WORLD(G@ME VERSION)',
    idols: ['315 STARS'],
    JOY: undefined,
    DAM: '4541-58',
    tags: ['WORLD TRE@SURE', 'G@ME VERSION'],
  },
]
